server {
  listen 80;
  server_name condar.app;
  location /.well-known/acme-challenge/ { root /var/www/certbot; }
  location / { return 301 https://morador.condar.app$request_uri; }
}
server {
  listen 443 ssl http2;
  server_name condar.app;
  ssl_certificate     /etc/letsencrypt/live/condar.app/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/condar.app/privkey.pem;
  return 301 https://morador.condar.app$request_uri;
}
